server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
# local machine logs
  # - job_name: test
    # pipeline_stages:
    # - regex:
    #     # expression: "^\\s*(?P<time>\\d{2}\\/\\d{2}\\s+\\d{2}:\\d{2}:\\d{2}.\\d+)\\s+\\[(?P<threadid>[0-9a-f]+)\\]\\s+(?P<optype>created|starting|completed)(.+?:\\s+)(?P<jobid>\\d+)(.+?:\\s+)(?P<jobname>[\\w]+)(?:(?:\\s+from\\s+host\\s+(?P<host>.+))|(?:\\s+by\\s+(?P<user>.+))|(?:,\\s+duration:\\s+(?P<dur>\\d+)\\s+msec,\\s+status:\\s(?P<endstatus>.+)))$"
    #     expression: "^\\s*(?P<time>\\d{2}\\/\\d{2}\\s+\\d{2}:\\d{2}:\\d{2}.\\d+)\\s+\\[(?P<threadid>[0-9a-f]+)\\]\\s+NOTICE:\\s+(?P<msgid>[\\-\\w\\d]+):.+command.+\"(?P<cmd>.+)\".*$"
    # - labels:
    #     time:
    #     threadid:
    #     command:
    #     msgid:
    #     cmd:
    #     # jobname:
    #     # jobid:
    #     # host:
    #     # user:
    #     # dur:
    #     # endstatus:
  - job_name: local
    static_configs:
    - targets:
        - localhost
      labels:
        job: smslogs
        __path__: /bugs/ddr/var/log/debug/sm/sms.info*
    pipeline_stages:
    - match:
        selector: '{job="smslogs"}'
        stages:
        - regex:
            expression: "^\\s*(?P<time>\\d{2}\\/\\d{2}\\s+\\d{2}:\\d{2}:\\d{2}.\\d+)\\s+\\[(?P<threadid>[0-9a-f]+)\\]\\s+(?P<optype>created|starting|completed)(.+?:\\s+)(?P<jobid>\\d+)(.+?:\\s+)(?P<jobname>[\\w]+)(?:(?:\\s+from\\s+host\\s+(?P<host>.+))|(?:\\s+by\\s+(?P<user>.+))|(?:,\\s+duration:\\s+(?P<dur>\\d+)\\s+msec,\\s+status:\\s(?P<endstatus>.+)))$"
        - labels:
            time:
            threadid:
            optype:
            jobname:
            jobid:
            host:
            user:
            dur:
            endstatus:
  - job_name: local
    static_configs:
    - targets:
        - localhost
      labels:
        job: ddsh
        __path__: /bugs/ddr/var/log/debug/sm/ddsh.info*
    pipeline_stages:
    - match:
        selector: '{job="ddsh"}'
        stages:
        - regex:
            expression: "^\\s*(?P<time>\\d{2}\\/\\d{2}\\s+\\d{2}:\\d{2}:\\d{2}.\\d+)\\s+\\[(?P<threadid>[0-9a-f]+)\\]\\s+NOTICE:\\s+(?P<msgid>[\\-\\w\\d]+):.+command.+\"(?P<cmd>.+)\".*$"
        - labels:
            time:
            threadid:
            command:
            msgid:
            cmd:

## docker logs

#- job_name: docker 
#  pipeline_stages:
#    - docker: {}
#  static_configs:
#    - labels:
#        job: docker
#        __path__: /var/lib/docker/containers/*/*-json.log

# syslog target

#- job_name: syslog
#  syslog:
#    listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
#    idle_timeout: 60s
#    label_structured_data: yes
#    labels:
#      job: "syslog"
#  relabel_configs:
#    - source_labels: ['__syslog_message_hostname']
#      target_label: 'host'